[profile.default]
src = "src"
out = "out"
libs = ["lib", ".deps/npm"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "prb-math/=.deps/npm/prb-math/",
    "@uniswap/v2-core/=.deps/npm/v2-core/",
    "@uniswap/v3-core/=.deps/npm/v3-core/",
    "@uniswap/v3-periphery/=.deps/npm/v3-periphery/",
    "@uniswap/v4-core/=.deps/npm/v4-core/src/",
    "@uniswap/universal-router/=.deps/npm/universal-router/contracts/"
]

[profile.default.metadata]
bytecode_hash = "none"

[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/yMachMSAgUaT5L0Y02bsz87hg0Cu4Bud"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
arbitrum = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options